// =======================================================================================
//                                                                           Core Settings
//                                                                           =============
buildscript {
    repositories {
        mavenCentral()
    }
}

plugins {
    // TODO hakiba riot v6移行後は npm コマンドはgradleから直接実行しないので削除して良い by 2022/06/01
    // #gradle8 mooworkが新しいGradleに対応していなくて落ちるので別のものを導入 by jflute (2024/11/02)
    //id 'com.moowork.node' version '1.3.1'               // ./gradlew npm_xxx
    id 'com.github.node-gradle.node' version "7.1.0"

    // #gradle8 upgrade to latest version to avoid redundant getter errors by jflute (2024/11/03)
    id 'com.github.hierynomus.license' version '0.16.1' // ./gradlew licenseMain

    // 複数IDE開発のためにspotless formatterを入れてみる by jflute (2024/11/02)
    // https://github.com/dbflute/dbflute-intro/issues/503
    // https://plugins.gradle.org/plugin/com.diffplug.spotless
    id 'com.diffplug.spotless' version "7.0.0.BETA4"
}

apply plugin: 'application'    // ./gradlew run: can execute main() of the 'mainClassName' variable
apply plugin: 'war'            // ./gradlew build: you know
apply plugin: 'project-report' // ./gradlew dependencyReport: can make dependencies.txt


// =======================================================================================
//                                                                              Basic Info
//                                                                              ==========
group = 'org.dbflute'
version = '0.6.0'

ext {
    encoding = 'UTF-8'

    versions =
        [
            // Basic Resource
            jdk        : '1.8',
            gradle     : '4.2',
            node       : '16.15.0',

            // Main Framework
            dbflute    : '1.2.6',
            h2         : '1.4.199',
            lastaflute : '1.2.3',

            // Partner Library
            slf4j      : '1.7.30',
            logback    : '1.2.3',
            jettyboot  : '0.5.1',
            lastameta  : '0.5.2',
            swaggerui  : '3.22.1',

            // GoodNeighbor Library
            commonslang: '3.9',
            commonsio  : '2.6',

            // Testing
            junit      : '4.13.1',
            utflute    : '0.9.4'
        ]
}


// =======================================================================================
//                                                                                 Plug-in
//                                                                                 =======
// _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
// original hook points, related to 'refresh' task
// these should be defined before including gradlePlugin
// because they can add their own process to the tasks
// _/_/_/_/_/_/_/_/_/_/
task refreshResource {
}

task refreshResourceAfter {
}

// include plugin's gradle settings (using application settings, e.g. versions)
fileTree(dir: 'gradle/gradlePlugin', includes: ['*.gradle']).each { apply from: it }


// =======================================================================================
//                                                                                 Library
//                                                                                 =======
repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url 'https://oss.sonatype.org/content/groups/public'
    }
}

dependencies { // #gradle8 compileが使えなくなったのでimplementationを使うようにした by jflute (2024/11/02)
    // Main Framework
    implementation "org.dbflute:dbflute-runtime:${versions.dbflute}"
    runtimeOnly "com.h2database:h2:${versions.h2}"
    implementation "org.lastaflute:lastaflute:${versions.lastaflute}"

    // Partner Library
    implementation "javax.transaction:javax.transaction-api:1.2"
    implementation "org.slf4j:slf4j-api:${versions.slf4j}"
    runtimeOnly "ch.qos.logback:logback-classic:${versions.logback}"
    implementation "javax.servlet:javax.servlet-api:3.1.0"
    implementation "org.dbflute.jetty:jetty-boot:${versions.jettyboot}"
    implementation "org.lastaflute.meta:lasta-meta:${versions.lastameta}"
    runtimeOnly "org.webjars:swagger-ui:${versions.swaggerui}"

    // GoodNeighbor Library
    implementation "org.apache.commons:commons-lang3:${versions.commonslang}"
    implementation "commons-io:commons-io:${versions.commonsio}"

    // Testing
    testImplementation "junit:junit:${versions.junit}"
    testImplementation "org.dbflute.utflute:utflute-lastaflute:${versions.utflute}"
}


// =======================================================================================
//                                                                               Packaging
//                                                                               =========
mainClassName = 'org.dbflute.intro.IntroBoot'

war {
    webAppDirectory = file('src/main/webapp')

    def embeddedArtifactList = ['javax.servlet-api', 'jetty-boot', 'jetty-all']
    // #gradle8 runtimeClasspathを使うようにした by jflute (2024/11/02)
    //configurations.runtimeClasspath.collect { file ->
    //    if (embeddedArtifactList.any { file.getName().startsWith(it) }) {
    //        from(file.isDirectory() ? file : zipTree(file)) {
    //            exclude 'META-INF/*NOTICE*'
    //            exclude 'META-INF/*LICENSE*'
    //            exclude 'META-INF/*DEPENDENCIES*'
    //            exclude 'META-INF/maven/**'
    //        }
    //    }
    //}
    //rootSpec.exclude(embeddedArtifactList.collect { "**/${it}-*.jar" })
    //from fileTree(dir: sourceSets.main.output.classesDirs, includes: ["${mainClassName.replace('.', '/')}*.class"])
    //from fileTree(dir: file('dist'), include: '**/**')

    includeEmptyDirs = false

    version = ''
    archivesBaseName = 'dbflute-intro'

    // #gradle8 extensionが使えなくなって、Gradleのソースコードを真似たやり方 by jflute (2024/11/02)
    //archiveExtension.set('jar')

    def scmBranch = 'unknown'
    def scmRevision = 'unknown'

    try {
        scmBranch = 'git branch --contains'.execute().text.trim() - '* '
        scmRevision = 'git rev-parse HEAD'.execute().text.trim()
    } catch (Exception ignored) {
    }

    manifest {
        attributes 'Implementation-Title': project.name
        attributes 'Implementation-Version': project.version
        attributes 'SCM-Branch': scmBranch
        attributes 'SCM-Revision': scmRevision
        attributes 'Build-Timestamp': new java.text.SimpleDateFormat('yyyy/MM/dd HH:mm:ss.SSS').format(new Date())
        attributes 'Jenkins-Build-Number': System.getenv()['BUILD_NUMBER'] ?: ''
        attributes 'Main-Class': mainClassName
    }

    // license
    from('LICENSE') {
        into 'META-INF'
        rename('LICENSE', 'LICENSE.txt')
    }
    from('etc/dist-license') {
        into 'META-INF/dist-license'
    }
}


// =======================================================================================
//                                                                                 License
//                                                                                 =======
license {
    header file('LICENSE_HEADER')
    strictCheck true
    include "**/*.java"
    mapping {
        java = 'SLASHSTAR_STYLE'
    }
}


// =======================================================================================
//                                                                                 Refresh
//                                                                                 =======
task refresh(dependsOn: ['refreshResource', 'refreshResourceAfter', 'eclipse'])
tasks['refreshResourceAfter'].dependsOn('refreshResource')
if (tasks.findByName('eclipseClasspath')) {
    tasks['eclipseClasspath'].dependsOn('refreshResource')
}


// =======================================================================================
//                                                                                 Release
//                                                                                 =======
// TODO hakiba riot v6移行後は releaseWithRiotV6 を release に置き換え、こちらは削除する
// フロントエンドのビルド -> バックエンドのビルド -> jar ファイルの作成の順番でリリース物を作成する
task release(dependsOn: ['build', 'manifest', 'cacheKey', 'npm_run_build']) {
    tasks['build'].mustRunAfter('npm_run_build')
    tasks['build'].mustRunAfter('manifest')
    tasks['build'].mustRunAfter('cacheKey')
}

task releaseWithRiotV6(dependsOn: ['build', 'manifest', 'cacheKey', 'buildFrontend']) {
    tasks['build'].mustRunAfter('buildFrontend')
    tasks['build'].mustRunAfter('manifest')
    tasks['build'].mustRunAfter('cacheKey')
}


// =======================================================================================
//                                                                                Spotless
//                                                                                ========
// Spotless plugin for Gradle
// https://github.com/diffplug/spotless/blob/main/plugin-gradle/README.md
spotless {
  java {
    // Gradleコマンドを実行するところから相対パス (実質プロジェクトルート)
    eclipse().configFile project.file("./etc/tools/eclipse/dbflute-eclipse-code-formatter.xml")

    // 自動生成クラスは除外
    targetExclude(
        'src/main/java/**/dbflute/**/allcommon/'
      , 'src/main/java/**/dbflute/**/bsbhv/'
      , 'src/main/java/**/dbflute/**/bsentity/'
      , 'src/main/java/**/dbflute/**/cbean/bs/'
      , 'src/main/java/**/dbflute/**/cbean/cq/bs/'
      , 'src/main/java/**/dbflute/**/cbean/cq/ciq/'
      , 'src/main/java/**/dbflute/**/cbean/nss/'
      , 'src/main/java/**/mylasta/action/*HtmlPath.java'
      , 'src/main/java/**/mylasta/action/*Labels.java'
      , 'src/main/java/**/mylasta/action/*Messages.java'
      , 'src/main/java/**/mylasta/appcls/'
      , 'src/main/java/**/mylasta/direction/*Config.java'
      , 'src/main/java/**/mylasta/direction/*Env.java'
    )

    importOrder('java', 'javax', 'org', 'com') // Eclipseのデフォルトに合わせて
    removeUnusedImports()
  }
}
