
-- =======================================================================================
--                                                                            Vendor Check
--                                                                            ============
CREATE TABLE VENDOR_CHECK (
	VENDOR_CHECK_ID NUMERIC(16) NOT NULL PRIMARY KEY,
	TYPE_OF_CHAR CHAR(3),
	TYPE_OF_VARCHAR VARCHAR(200),
	TYPE_OF_TEXT TEXT,
	TYPE_OF_TINYTEXT TINYTEXT,
	TYPE_OF_MEDIUMTEXT MEDIUMTEXT,
	TYPE_OF_LONGTEXT LONGTEXT,
	TYPE_OF_NUMERIC_DECIMAL NUMERIC(5, 3),
	TYPE_OF_NUMERIC_INTEGER NUMERIC(5, 0),
	TYPE_OF_NUMERIC_BIGINT NUMERIC(12, 0),
	TYPE_OF_DECIMAL_DECIMAL DECIMAL(5, 3),
	TYPE_OF_DECIMAL_INTEGER DECIMAL(5, 0),
	TYPE_OF_DECIMAL_BIGINT DECIMAL(12, 0),
	TYPE_OF_INTEGER INTEGER,
	TYPE_OF_BIGINT BIGINT,
	TYPE_OF_FLOAT FLOAT,
	TYPE_OF_DOUBLE DOUBLE,
	TYPE_OF_DATE DATE,
	TYPE_OF_DATETIME DATETIME,
	TYPE_OF_DATETIME_3_MILLIS DATETIME(3),
	TYPE_OF_DATETIME_6_MICROS DATETIME(6),
	TYPE_OF_TIMESTAMP TIMESTAMP,
	TYPE_OF_TIME TIME,
	TYPE_OF_YEAR YEAR,
	TYPE_OF_BOOLEAN BOOLEAN,
	TYPE_OF_BLOB BLOB(2000),
	TYPE_OF_TINYBLOB TINYBLOB,
	TYPE_OF_MEDIUMBLOB MEDIUMBLOB,
	TYPE_OF_LONGBLOB LONGBLOB,
	TYPE_OF_BINARY BINARY,
	TYPE_OF_VARBINARY VARBINARY(1000),
	TYPE_OF_ENUM ENUM('red','blue','yellow'),
	TYPE_OF_SET SET('red','blue','yellow'),
	COLUMN_EXCEPT_TEST INTEGER -- actually except
) ;

-- =======================================================================================
--                                                                               Long Name
--                                                                               =========
CREATE TABLE VENDOR_THE_LONG_AND_WINDING_TABLE_AND_COLUMN (
	THE_LONG_AND_WINDING_TABLE_AND_COLUMN_ID BIGINT NOT NULL PRIMARY KEY,
	THE_LONG_AND_WINDING_TABLE_AND_COLUMN_NAME VARCHAR(180) NOT NULL,
	SHORT_NAME VARCHAR(200) NOT NULL,
	SHORT_SIZE INTEGER NOT NULL,
	UNIQUE (THE_LONG_AND_WINDING_TABLE_AND_COLUMN_NAME)
);

CREATE TABLE VENDOR_THE_LONG_AND_WINDING_TABLE_AND_COLUMN_REF (
	THE_LONG_AND_WINDING_TABLE_AND_COLUMN_REF_ID BIGINT NOT NULL PRIMARY KEY,
	THE_LONG_AND_WINDING_TABLE_AND_COLUMN_ID BIGINT NOT NULL,
	THE_LONG_AND_WINDING_TABLE_AND_COLUMN_REF_DATE DATE NOT NULL,
	SHORT_DATE DATE NOT NULL
);

ALTER TABLE VENDOR_THE_LONG_AND_WINDING_TABLE_AND_COLUMN_REF ADD CONSTRAINT FK_VENDOR_THE_LONG_AND_WINDING_TABLE_AND_COLUMN_REF
 	FOREIGN KEY (THE_LONG_AND_WINDING_TABLE_AND_COLUMN_ID)
 	REFERENCES VENDOR_THE_LONG_AND_WINDING_TABLE_AND_COLUMN (THE_LONG_AND_WINDING_TABLE_AND_COLUMN_ID) ;

-- =======================================================================================
--                                                                              Large Data
--                                                                              ==========
-- for the test of large data
-- creating index is executed at take-finally
-- because of large data registered at load-data 
CREATE TABLE VENDOR_LARGE_DATA (
	LARGE_DATA_ID BIGINT NOT NULL PRIMARY KEY,
	STRING_INDEX VARCHAR(180) NOT NULL,
	STRING_NO_INDEX VARCHAR(180) NOT NULL,
	STRING_UNIQUE_INDEX VARCHAR(180) NOT NULL,
	INTFLG_INDEX INTEGER NOT NULL,
	NUMERIC_INTEGER_INDEX NUMERIC(8, 0) NOT NULL,
	NUMERIC_INTEGER_NO_INDEX NUMERIC(8, 0) NOT NULL,
	UNIQUE (STRING_UNIQUE_INDEX)
);

-- creating index after loading large data 
CREATE TABLE VENDOR_LARGE_DATA_REF (
	LARGE_DATA_REF_ID BIGINT NOT NULL PRIMARY KEY,
	LARGE_DATA_ID BIGINT NOT NULL,
	DATE_INDEX DATE NOT NULL,
	DATE_NO_INDEX DATE NOT NULL,
	TIMESTAMP_INDEX DATETIME NOT NULL,
	TIMESTAMP_NO_INDEX DATETIME NOT NULL,
	NULLABLE_DECIMAL_INDEX NUMERIC(12, 3),
	NULLABLE_DECIMAL_NO_INDEX NUMERIC(12, 3),
	SELF_PARENT_ID BIGINT
);

-- =======================================================================================
--                                                                               Name Auto
--                                                                               =========
-- /= = = = = = = = = = = = = = = = = = = = = = =
-- for the test of auto-generated constraint name
-- = = = = = = = = = =/
CREATE TABLE VENDOR_CONSTRAINT_NAME_AUTO_FOO (
	CONSTRAINT_NAME_AUTO_FOO_ID NUMERIC(16) NOT NULL PRIMARY KEY,
	CONSTRAINT_NAME_AUTO_FOO_NAME VARCHAR(50) NOT NULL,
	UNIQUE (CONSTRAINT_NAME_AUTO_FOO_NAME)
) ;

CREATE TABLE VENDOR_CONSTRAINT_NAME_AUTO_BAR (
	CONSTRAINT_NAME_AUTO_BAR_ID NUMERIC(16) NOT NULL PRIMARY KEY,
	CONSTRAINT_NAME_AUTO_BAR_NAME VARCHAR(50) NOT NULL,
	UNIQUE (CONSTRAINT_NAME_AUTO_BAR_NAME)
) ;

CREATE TABLE VENDOR_CONSTRAINT_NAME_AUTO_QUX (
	CONSTRAINT_NAME_AUTO_QUX_ID NUMERIC(16) NOT NULL PRIMARY KEY,
	CONSTRAINT_NAME_AUTO_QUX_NAME VARCHAR(50) NOT NULL,
	UNIQUE (CONSTRAINT_NAME_AUTO_QUX_NAME)
) ;

CREATE TABLE VENDOR_CONSTRAINT_NAME_AUTO_REF (
	CONSTRAINT_NAME_AUTO_REF_ID NUMERIC(16) NOT NULL PRIMARY KEY,
	CONSTRAINT_NAME_AUTO_FOO_ID NUMERIC(16) NOT NULL,
	CONSTRAINT_NAME_AUTO_BAR_ID NUMERIC(16) NOT NULL,
	CONSTRAINT_NAME_AUTO_QUX_ID NUMERIC(16) NOT NULL,
	CONSTRAINT_NAME_AUTO_CORGE_ID NUMERIC(16) NOT NULL,
	CONSTRAINT_NAME_AUTO_UNIQUE VARCHAR(50) NOT NULL,
	FOREIGN KEY(CONSTRAINT_NAME_AUTO_FOO_ID) REFERENCES VENDOR_CONSTRAINT_NAME_AUTO_FOO(CONSTRAINT_NAME_AUTO_FOO_ID),
	-- for test of schema diff
	-- FOREIGN KEY(CONSTRAINT_NAME_AUTO_CORGE_ID) REFERENCES VENDOR_CONSTRAINT_NAME_AUTO_BAR(CONSTRAINT_NAME_AUTO_BAR_ID),
	-- FOREIGN KEY(CONSTRAINT_NAME_AUTO_BAR_ID) REFERENCES VENDOR_CHECK(VENDOR_CHECK_ID),
	FOREIGN KEY(CONSTRAINT_NAME_AUTO_BAR_ID) REFERENCES VENDOR_CONSTRAINT_NAME_AUTO_BAR(CONSTRAINT_NAME_AUTO_BAR_ID),
	FOREIGN KEY(CONSTRAINT_NAME_AUTO_QUX_ID) REFERENCES VENDOR_CONSTRAINT_NAME_AUTO_QUX(CONSTRAINT_NAME_AUTO_QUX_ID),
	UNIQUE (CONSTRAINT_NAME_AUTO_UNIQUE)
) ;

-- =======================================================================================
--                                                                                  Dollar
--                                                                                  ======
create table VENDOR_$_DOLLAR (
	VENDOR_$_DOLLAR_ID INTEGER NOT NULL PRIMARY KEY,
	VENDOR_$_DOLLAR_NAME VARCHAR(32)
);
