
-- creating index after loading large data 
ALTER TABLE VENDOR_LARGE_DATA_REF ADD CONSTRAINT FK_VENDOR_LARGE_DATA_REF_DATA 
	FOREIGN KEY (LARGE_DATA_ID) REFERENCES VENDOR_LARGE_DATA (LARGE_DATA_ID) ;

ALTER TABLE VENDOR_LARGE_DATA_REF ADD CONSTRAINT FK_VENDOR_LARGE_DATA_REF_SELF 
	FOREIGN KEY (SELF_PARENT_ID) REFERENCES VENDOR_LARGE_DATA_REF (LARGE_DATA_REF_ID) ;

CREATE INDEX IX_LARGE_DATA_STRING ON VENDOR_LARGE_DATA(STRING_INDEX) ;
CREATE INDEX IX_LARGE_DATA_NUMERIC_INTEGER ON VENDOR_LARGE_DATA(NUMERIC_INTEGER_INDEX) ;

CREATE INDEX IX_LARGE_DATA_REF_DATE ON VENDOR_LARGE_DATA_REF(DATE_INDEX) ;
CREATE INDEX IX_LARGE_DATA_REF_TIMESTAMP ON VENDOR_LARGE_DATA_REF(TIMESTAMP_INDEX) ;
CREATE INDEX IX_LARGE_DATA_REF_NULLABLE_DEC ON VENDOR_LARGE_DATA_REF(NULLABLE_DECIMAL_INDEX) ;
