
create table CLS_TARGET_DATABASE(
    DATABASE_CODE VARCHAR(10) NOT NULL PRIMARY KEY,
    DATABASE_NAME VARCHAR(100) NOT NULL,
    JDBC_DRIVER_FQCN VARCHAR(100) NOT NULL,
    URL_TEMPLATE VARCHAR(100) NOT NULL,
    DEFAULT_SCHEMA VARCHAR(10),
    SCHEMA_REQUIRED_FLG INTEGER NOT NULL,
    SCHEMA_UPPER_CASE_FLG INTEGER NOT NULL,
    USER_INPUT_ASSIST_FLG INTEGER NOT NULL,
    EMBEDDED_JAR_FLG INTEGER NOT NULL,
    DISPLAY_ORDER INTEGER NOT NULL
);

create table CLS_TARGET_LANGUAGE(
    LANGUAGE_CODE VARCHAR(10) NOT NULL PRIMARY KEY,
    LANGUAGE_NAME VARCHAR(100) NOT NULL,
    DISPLAY_ORDER INTEGER NOT NULL
);

create table CLS_TARGET_CONTAINER(
    CONTAINER_CODE VARCHAR(10) NOT NULL PRIMARY KEY,
    CONTAINER_NAME VARCHAR(100) NOT NULL,
    DISPLAY_ORDER INTEGER NOT NULL
);
